workflows:
  android-build:
    name: Android Build for Local Webview
    instance_type: mac_mini_medium
    environment:
      # Use Node for Capacitor setup
      node: 16
      java: 17

    scripts:
      - name: Install dependencies
        script: |
          npm install
          
      - name: Build web assets
        script: |
          npx cap copy
      
      - name: Build APK (Release Mode)
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      # Path to the resulting APK file
      - android/app/build/outputs/apk/release/*.apk
