workflows:
  android-build:
    name: Android Build for Local Webview
    # Changed instance_type to a valid member (e.g., linux_x2 or mac_mini_m1)
    # Using 'linux_x2' as it is usually free/cheap and powerful enough.
    instance_type: linux_x2 
    max_build_duration: 60
    
    environment:
      # We need an environment that supports Node and Android SDK (which Linux/Mac types do)
      node: 16
      java: 17

    scripts:
      - name: Install dependencies
        script: npm install
          
      - name: Build web assets
        script: npx cap copy
      
      - name: Build APK (Release Mode)
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      # Path to the resulting APK file
      - android/app/build/outputs/apk/release/*.apk


